name: Rage Table Flip
source: file://rage-table-flip.mp4
keywords:
  - table flip
  - flipping tables
  - rage comic
  - rage
  - angry
text:
  - style: upper
    color: black
    font: thick
    anchor_x: 0.03
    anchor_y: 0.02
    angle: 0.0
    scale_x: 0.94
    scale_y: 0.16
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: black
    font: thick
    anchor_x: 0.03
    anchor_y: 0.80
    angle: 0.0
    scale_x: 0.94
    scale_y: 0.17
    align: center
    start: 0.0
    stop: 1.0
example:
  - WHEN THE CODE DOESN'T WORK
  - AND YOU DON'T KNOW WHY
