name: Posted it again award
source: https://imgflip.com/meme/525022598/Posted-it-again-award
keywords:
  - clown
  - soldier
  - army
  - military
  - clown soldier
  - guys we are looking for
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.07
    angle: 0.0
    scale_x: 0.235
    scale_y: 0.8
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.255
    anchor_y: 0.07
    angle: 0.0
    scale_x: 0.235
    scale_y: 0.8
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.5
    anchor_y: 0.07
    angle: 0.0
    scale_x: 0.235
    scale_y: 0.8
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.745
    anchor_y: 0.07
    angle: 0.0
    scale_x: 0.245
    scale_y: 0.8
    align: center
    start: 0.0
    stop: 1.0
example:
  - Lurkers
  - My meme about a niche topic
  - The rest of the subreddit
  - Mods looking for rule breakers
