name: Moe Throws Barney
source: file://moe-throws-barney.mp4
keywords:
  - moe
  - simpsons
  - dusting hands
  - barney
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.02
    anchor_y: 0.005
    angle: 0.0
    scale_x: 0.96
    scale_y: 0.11
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.02
    anchor_y: 0.88
    angle: 0.0
    scale_x: 0.96
    scale_y: 0.10
    align: center
    start: 0.0
    stop: 1.0
example:
  - Me deleting an app
  - Me
